/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arackiralama;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ASUS
 */
public class admin extends javax.swing.JFrame {
   dbAdmin db = new dbAdmin();


    /**
     * Creates new form aracKiralama
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arabalarTable = new javax.swing.JTable();
        searchText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kiralikTable = new javax.swing.JTable();
        searchText1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        kullaniciTable = new javax.swing.JTable();
        searchText2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));

        jTabbedPane1.setBackground(new java.awt.Color(204, 153, 255));
        jTabbedPane1.setForeground(new java.awt.Color(51, 0, 51));
        jTabbedPane1.setToolTipText("arabalar");

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        arabalarTable.setBackground(new java.awt.Color(0, 153, 255));
        arabalarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "marka", "model", "fiyat", "bu tarihe kadar kiralanabilir", "sil", "değiştir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(arabalarTable);
        if (arabalarTable.getColumnModel().getColumnCount() > 0) {
            arabalarTable.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        searchText.setBackground(new java.awt.Color(255, 153, 153));
        searchText.setForeground(java.awt.Color.gray);
        searchText.setText("Search .....");
        searchText.setToolTipText("");
        searchText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFocusLost(evt);
            }
        });
        searchText.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                searchTextİnputMethodTextChanged(evt);
            }
        });
        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTextKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(130, 1, 130));
        jButton1.setText("Araba Ekle");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(9, 123, 9));
        jButton2.setText("Yenile");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("arabalar", jPanel1);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        kiralikTable.setBackground(new java.awt.Color(255, 153, 153));
        kiralikTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "kiralık id", "arabanın id ", "müşteri id", "marka", "model", "alış tarihi", "dönüş tarihi", "değiştir", "sil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(kiralikTable);

        searchText1.setBackground(new java.awt.Color(255, 153, 153));
        searchText1.setForeground(java.awt.Color.darkGray);
        searchText1.setText("Search .....");
        searchText1.setToolTipText("");
        searchText1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchText1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchText1FocusLost(evt);
            }
        });
        searchText1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                searchText1İnputMethodTextChanged(evt);
            }
        });
        searchText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchText1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchText1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchText1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchText1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchText1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("kiralık arabalar", jPanel2);

        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentShown(evt);
            }
        });

        kullaniciTable.setBackground(new java.awt.Color(255, 51, 51));
        kullaniciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ad", "soyad", "telefon", "adres", "sifre", "email", "admin", "değiştir", "sil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(kullaniciTable);

        searchText2.setBackground(new java.awt.Color(255, 153, 153));
        searchText2.setForeground(new java.awt.Color(51, 51, 51));
        searchText2.setText("Search .....");
        searchText2.setToolTipText("");
        searchText2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchText2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchText2FocusLost(evt);
            }
        });
        searchText2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                searchText2İnputMethodTextChanged(evt);
            }
        });
        searchText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchText2ActionPerformed(evt);
            }
        });
        searchText2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchText2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchText2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchText2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchText2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchText2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("kullanıcılar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("arabalar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        db.arabalar(arabalarTable);
        
        Action delete = new AbstractAction()
{
    public void actionPerformed(ActionEvent e)
    {
        JTable table = (JTable)e.getSource();
        int modelRow = Integer.valueOf( e.getActionCommand() );
        if(db.arabaSil((String) table.getValueAt(modelRow,0))){
                JOptionPane.showMessageDialog(null, "bu araba silinmiş", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
                JOptionPane.showMessageDialog(null, "bu araba silinmemiş", "", JOptionPane.INFORMATION_MESSAGE);
        }

     db.arabalar(arabalarTable);
    }
};
ButtonColumn buttonColumn = new ButtonColumn(arabalarTable, delete, 5);
buttonColumn.setMnemonic(KeyEvent.VK_D);

Action degistir = new AbstractAction()
{
    public void actionPerformed(ActionEvent e)
    {
        JTable table = (JTable)e.getSource();
        int modelRow = Integer.valueOf( e.getActionCommand() );
        String fiyat = (String) table.getValueAt(modelRow,3);
        String arabaninId = (String) table.getValueAt(modelRow,0);
        String alMarka = (String) table.getValueAt(modelRow,1);
        String alModel = (String) table.getValueAt(modelRow,2);
       String guncelleDurum =  db.arabaGuncelle(arabaninId, alMarka, alModel, fiyat);
        JOptionPane.showMessageDialog(null, guncelleDurum, "", JOptionPane.INFORMATION_MESSAGE);
     db.arabalar(arabalarTable);
     
    }
};
ButtonColumn buttonColumn2 = new ButtonColumn(arabalarTable, degistir, 6);
buttonColumn2.setMnemonic(KeyEvent.VK_D);
    }//GEN-LAST:event_jPanel1ComponentShown

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        db.kiralananArabalar(kiralikTable);
        Action delete = new AbstractAction()
{
    public void actionPerformed(ActionEvent e)
    {
        JTable table = (JTable)e.getSource();
        int modelRow = Integer.valueOf( e.getActionCommand() );
        if(db.kiralananSil((String) table.getValueAt(modelRow,0))){
                JOptionPane.showMessageDialog(null, "bu satır silinmiş", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
                JOptionPane.showMessageDialog(null, "bu satır silinmemiş", "", JOptionPane.INFORMATION_MESSAGE);
        }

        db.kiralananArabalar(kiralikTable);
    }
};
ButtonColumn buttonColumn = new ButtonColumn(kiralikTable, delete, 8);
buttonColumn.setMnemonic(KeyEvent.VK_D);

Action degistir = new AbstractAction()
{
    public void actionPerformed(ActionEvent e)
    {
        JTable table = (JTable)e.getSource();
        int modelRow = Integer.valueOf( e.getActionCommand() );
        String kiralananId = (String) table.getValueAt(modelRow,0);
        String arabaninId = (String) table.getValueAt(modelRow,1);
        String musteriId = (String) table.getValueAt(modelRow,2);
        String marka = (String) table.getValueAt(modelRow,3);
        String model = (String) table.getValueAt(modelRow,4);
        String alis_tarihi = (String) table.getValueAt(modelRow,5);
        String donus_tarihi = (String) table.getValueAt(modelRow,6);
       String guncelleDurum =  db.kiralananGuncelle(kiralananId ,musteriId,arabaninId, alis_tarihi, donus_tarihi, marka , model);
        JOptionPane.showMessageDialog(null, guncelleDurum, "", JOptionPane.INFORMATION_MESSAGE);
        db.kiralananArabalar(kiralikTable);

    }
};
ButtonColumn buttonColumn2 = new ButtonColumn(kiralikTable, degistir, 7);
buttonColumn2.setMnemonic(KeyEvent.VK_D);
    }//GEN-LAST:event_jPanel2ComponentShown

    private void searchTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusGained
    
       if (searchText.getText().equals("Search .....")) {
            searchText.setText("");
            searchText.setForeground(Color.BLACK);
        }

    
    }//GEN-LAST:event_searchTextFocusGained

    private void searchTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusLost
        if (searchText.getText().isEmpty()) {
            searchText.setForeground(Color.GRAY);
            searchText.setText("Search .....");
        }    }//GEN-LAST:event_searchTextFocusLost

    private void searchTextİnputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_searchTextİnputMethodTextChanged
    }//GEN-LAST:event_searchTextİnputMethodTextChanged

    private void searchTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyPressed
    }//GEN-LAST:event_searchTextKeyPressed

    private void searchTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyTyped
    }//GEN-LAST:event_searchTextKeyTyped

    private void searchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyReleased
        TableRowSorter<TableModel> rowSorter  = new TableRowSorter<>(arabalarTable.getModel());
        arabalarTable.setRowSorter(rowSorter);

        String text = searchText.getText();
  if (text.trim().length() == 0) {
     rowSorter.setRowFilter(null);
  } else {
     rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
  }     }//GEN-LAST:event_searchTextKeyReleased

    private void searchText1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchText1FocusGained
    
       if (searchText1.getText().equals("Search .....")) {
            searchText1.setText("");
            searchText1.setForeground(Color.BLACK);
        }    }//GEN-LAST:event_searchText1FocusGained

    private void searchText1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchText1FocusLost
        if (searchText1.getText().isEmpty()) {
            searchText1.setForeground(Color.GRAY);
            searchText1.setText("Search .....");
        }             }//GEN-LAST:event_searchText1FocusLost

    private void searchText1İnputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_searchText1İnputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText1İnputMethodTextChanged

    private void searchText1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchText1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText1KeyPressed

    private void searchText1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchText1KeyReleased
        TableRowSorter<TableModel> rowSorter  = new TableRowSorter<>(kiralikTable.getModel());
        kiralikTable.setRowSorter(rowSorter);

        String text = searchText1.getText();
  if (text.trim().length() == 0) {
     rowSorter.setRowFilter(null);
  } else {
     rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
  }     }//GEN-LAST:event_searchText1KeyReleased

    private void searchText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchText1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    arabaEkle arabaEkleForm = new arabaEkle();
    arabaEkleForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        db.arabalar(arabalarTable);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchText2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchText2FocusGained
       if (searchText2.getText().equals("Search .....")) {
            searchText2.setText("");
            searchText2.setForeground(Color.BLACK);
        }    }//GEN-LAST:event_searchText2FocusGained

    private void searchText2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchText2FocusLost
            if (searchText2.getText().isEmpty()) {
            searchText2.setForeground(Color.GRAY);
            searchText2.setText("Search .....");
        }  
    }//GEN-LAST:event_searchText2FocusLost

    private void searchText2İnputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_searchText2İnputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText2İnputMethodTextChanged

    private void searchText2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchText2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText2KeyPressed

    private void searchText2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchText2KeyReleased
        TableRowSorter<TableModel> rowSorter  = new TableRowSorter<>(kullaniciTable.getModel());
        kullaniciTable.setRowSorter(rowSorter);

        String text = searchText2.getText();
  if (text.trim().length() == 0) {
     rowSorter.setRowFilter(null);
  } else {
     rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
  }       }//GEN-LAST:event_searchText2KeyReleased

    private void searchText2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchText2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText2KeyTyped

    private void searchText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText2ActionPerformed

    private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown
  db.kullanicilar(kullaniciTable);
        Action delete = new AbstractAction()
{
    public void actionPerformed(ActionEvent e)
    {
        JTable table = (JTable)e.getSource();
        int modelRow = Integer.valueOf( e.getActionCommand() );
        if(db.kullaniciSil((String) table.getValueAt(modelRow,0))){
                JOptionPane.showMessageDialog(null, "bu kullanici silinmiş", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
                JOptionPane.showMessageDialog(null, "bu kullanici silinmemiş", "", JOptionPane.INFORMATION_MESSAGE);
        }

  db.kullanicilar(kullaniciTable);
    }
};
ButtonColumn buttonColumn = new ButtonColumn(kullaniciTable, delete, 9);
buttonColumn.setMnemonic(KeyEvent.VK_D);

Action degistir = new AbstractAction()
{
    public void actionPerformed(ActionEvent e)
    {
        JTable table = (JTable)e.getSource();
        int modelRow = Integer.valueOf( e.getActionCommand() );
        String kiralananId = (String) table.getValueAt(modelRow,0);
        String ad = (String) table.getValueAt(modelRow,1);
        String soyad = (String) table.getValueAt(modelRow,2);
        String telefon = (String) table.getValueAt(modelRow,3);
        String adres = (String) table.getValueAt(modelRow,4);
        String sifre = (String) table.getValueAt(modelRow,5);
        String email = (String) table.getValueAt(modelRow,6);
       String guncelleDurum =  db.kullaniciGuncelle(kiralananId ,ad,soyad, telefon, adres, sifre , email);
        JOptionPane.showMessageDialog(null, guncelleDurum, "", JOptionPane.INFORMATION_MESSAGE);
  db.kullanicilar(kullaniciTable);

    }
};
ButtonColumn buttonColumn2 = new ButtonColumn(kullaniciTable, degistir, 8);
buttonColumn2.setMnemonic(KeyEvent.VK_D);
Action adminYap = new AbstractAction()
{
    public void actionPerformed(ActionEvent e)
    {
        JTable table = (JTable)e.getSource();
        int modelRow = Integer.valueOf( e.getActionCommand() );
        String kiralananId = (String) table.getValueAt(modelRow,0);
        String adminDurum = (String) table.getValueAt(modelRow,7);
        String admin = "false";
        if(adminDurum.contains("Admin Yap")){
        admin = "true";
        }
       String guncelleDurum =  db.kullaniciAdminYap(kiralananId ,admin);
       JOptionPane.showMessageDialog(null, guncelleDurum, "", JOptionPane.INFORMATION_MESSAGE);
       db.kullanicilar(kullaniciTable);

    }
};
ButtonColumn buttonColumn3 = new ButtonColumn(kullaniciTable, adminYap, 7);
buttonColumn3.setMnemonic(KeyEvent.VK_D);
     }//GEN-LAST:event_jPanel4ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable arabalarTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable kiralikTable;
    private javax.swing.JTable kullaniciTable;
    private javax.swing.JTextField searchText;
    private javax.swing.JTextField searchText1;
    private javax.swing.JTextField searchText2;
    // End of variables declaration//GEN-END:variables
}
