/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arackiralama;
import javax.swing.JOptionPane;


/**
 *
 * @author ASUS
 */
public class Kayit extends javax.swing.JFrame {
   DBKatmani db = new DBKatmani();

    /**
     * Creates new form register
     */
    public Kayit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adTextBox = new javax.swing.JTextField();
        soyadTextBox = new javax.swing.JTextField();
        telefonTextBox = new javax.swing.JTextField();
        adresTextBox = new javax.swing.JTextField();
        emailTextBox = new javax.swing.JTextField();
        sifreTextBox = new javax.swing.JTextField();
        kaydolButton = new javax.swing.JButton();
        iptalButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        girisFormButton = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kaydol");
        setLocation(new java.awt.Point(500, 200));

        jPanel1.setBackground(new java.awt.Color(43, 188, 188));

        jLabel1.setText("Ad");

        jLabel2.setText("Soyad");

        jLabel3.setText("Telefon");

        jLabel6.setText("Adres");

        jLabel5.setText("E mail");

        jLabel4.setText("Şifre");

        adTextBox.setName("adTextBox"); // NOI18N
        adTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adTextBoxActionPerformed(evt);
            }
        });

        soyadTextBox.setName("soyadTextBox"); // NOI18N
        soyadTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyadTextBoxActionPerformed(evt);
            }
        });

        telefonTextBox.setName("telefonTextBox"); // NOI18N
        telefonTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonTextBoxActionPerformed(evt);
            }
        });

        adresTextBox.setName("adresTextBox"); // NOI18N
        adresTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresTextBoxActionPerformed(evt);
            }
        });

        emailTextBox.setName("emailTextBox"); // NOI18N
        emailTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextBoxActionPerformed(evt);
            }
        });

        sifreTextBox.setName("sifreTextBox"); // NOI18N

        kaydolButton.setBackground(new java.awt.Color(255, 255, 51));
        kaydolButton.setText("Kaydol");
        kaydolButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kaydolButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kaydolButtonClicked(evt);
            }
        });
        kaydolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydolButtonActionPerformed(evt);
            }
        });

        iptalButton.setBackground(new java.awt.Color(255, 12, 0));
        iptalButton.setText("İptal");
        iptalButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iptalButton.setPreferredSize(new java.awt.Dimension(65, 23));
        iptalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iptalButtonClicked(evt);
            }
        });
        iptalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptalButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("  hesabiniz var mı? ");

        girisFormButton.setBackground(new java.awt.Color(204, 153, 255));
        girisFormButton.setText("Giriş Yap");
        girisFormButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        girisFormButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                girisFormButtonMouseClicked(evt);
            }
        });
        girisFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisFormButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(adTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(soyadTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telefonTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(adresTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sifreTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iptalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kaydolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(girisFormButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(soyadTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telefonTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(adresTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sifreTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kaydolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iptalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(girisFormButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adTextBox.getAccessibleContext().setAccessibleName("adTextBox");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonTextBoxActionPerformed

    private void soyadTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyadTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyadTextBoxActionPerformed

    private void adresTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresTextBoxActionPerformed

    private void adTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adTextBoxActionPerformed

    private void girisFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisFormButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_girisFormButtonActionPerformed

    private void kaydolButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaydolButtonClicked
      
        try{
      String ad = adTextBox.getText();
      String soyad = soyadTextBox.getText();
      String telefon = telefonTextBox.getText();
      String adres = adresTextBox.getText();
      String email = emailTextBox.getText();
      String sifre = sifreTextBox.getText();

         String kayitDurum  =   db.kayit(ad, soyad, telefon, adres, email, sifre);
         if(kayitDurum.contains("duplicate key")){
         kayitDurum = "Bu email başka bir hesapta kullanılıyor";
         }
        JOptionPane.showMessageDialog(null, kayitDurum, "", JOptionPane.INFORMATION_MESSAGE);

      }
      catch(Exception ex){
      
      }

    }//GEN-LAST:event_kaydolButtonClicked

    private void emailTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextBoxActionPerformed

    private void girisFormButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisFormButtonMouseClicked
        // TODO add your handling code here:
    Giris girisForm = new Giris();
    girisForm.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_girisFormButtonMouseClicked

    private void kaydolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydolButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kaydolButtonActionPerformed

    private void iptalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptalButtonActionPerformed
      
    }//GEN-LAST:event_iptalButtonActionPerformed

    private void iptalButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iptalButtonClicked
    dispose();
    }//GEN-LAST:event_iptalButtonClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adTextBox;
    private javax.swing.JTextField adresTextBox;
    private javax.swing.JTextField emailTextBox;
    private javax.swing.JButton girisFormButton;
    private javax.swing.JButton iptalButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kaydolButton;
    private javax.swing.JTextField sifreTextBox;
    private javax.swing.JTextField soyadTextBox;
    private javax.swing.JTextField telefonTextBox;
    // End of variables declaration//GEN-END:variables
}
