/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arackiralama;

import static arackiralama.aracKiralama.arabaninUcret;
import static arackiralama.aracKiralama.musaitTarih;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.concurrent.TimeUnit;
import javafx.scene.control.DatePicker;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class rentForm extends javax.swing.JFrame {
 DBKatmani db = new DBKatmani();
    /**
     * Creates new form rentForm
     */
    public rentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        alisTarihi = new org.jdesktop.swingx.JXDatePicker();
        donusTarihi = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        alButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ucretLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        alisTarihi.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                alisTarihiPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        donusTarihi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                donusTarihiFocusLost(evt);
            }
        });
        donusTarihi.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
                donusTarihiPopupMenuCanceled(evt);
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                donusTarihiPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        donusTarihi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                donusTarihiMouseExited(evt);
            }
        });
        donusTarihi.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                donusTarihiİnputMethodTextChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("alış tarihi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("dönüş tarihi");

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Ücret hesapla");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        alButton.setBackground(new java.awt.Color(153, 0, 51));
        alButton.setText("Araba al");
        alButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alButtonMouseClicked(evt);
            }
        });
        alButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alButtonActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 204, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ucret");

        ucretLabel.setBackground(new java.awt.Color(255, 204, 0));
        ucretLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ucretLabel.setText("00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alisTarihi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(donusTarihi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(ucretLabel))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alisTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(donusTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ucretLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donusTarihiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_donusTarihiFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_donusTarihiFocusLost

    private void donusTarihiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donusTarihiMouseExited
    }//GEN-LAST:event_donusTarihiMouseExited

    private void donusTarihiPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_donusTarihiPopupMenuWillBecomeInvisible
        if(alisTarihi.getDate() == null){
                JOptionPane.showMessageDialog(null, "Alış tarihi seçiniz", "", JOptionPane.INFORMATION_MESSAGE);

        }else if(donusTarihi.getDate() == null){
                JOptionPane.showMessageDialog(null, "Dönüş tarihi seçiniz", "", JOptionPane.INFORMATION_MESSAGE);

        }else{
        System.out.println();
  long ddd;
  java.sql.Date alisDate = new java.sql.Date(alisTarihi.getDate().getTime());
  java.sql.Date donusDate = new java.sql.Date(donusTarihi.getDate().getTime());
        ddd = getDifferenceDays(alisDate,donusDate);
        System.out.println(ddd);
        
        }  

    }//GEN-LAST:event_donusTarihiPopupMenuWillBecomeInvisible

    private void alisTarihiPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_alisTarihiPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_alisTarihiPopupMenuWillBecomeInvisible

    private void donusTarihiİnputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_donusTarihiİnputMethodTextChanged
    }//GEN-LAST:event_donusTarihiİnputMethodTextChanged

    private void donusTarihiPopupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_donusTarihiPopupMenuCanceled
        // TODO add your handling code here:
    }//GEN-LAST:event_donusTarihiPopupMenuCanceled

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(alisTarihi.getDate() == null){
                JOptionPane.showMessageDialog(null, "Alış tarihi seçiniz", "", JOptionPane.INFORMATION_MESSAGE);

        }else if(donusTarihi.getDate() == null){
                JOptionPane.showMessageDialog(null, "Dönüş tarihi seçiniz", "", JOptionPane.INFORMATION_MESSAGE);

        }else{
              long sure;
         java.sql.Date musaitTarihh = Date.valueOf("4020-05-11");
         java.sql.Date currentDate = new java.sql.Date(Calendar.getInstance().getTime().getTime());
         java.sql.Date alisDate = new java.sql.Date(alisTarihi.getDate().getTime());
         java.sql.Date donusDate = new java.sql.Date(donusTarihi.getDate().getTime());
         try {
          musaitTarihh = Date.valueOf(aracKiralama.musaitTarih);

         }catch(Exception e) {
             
         
         }

        sure = getDifferenceDays(donusDate,musaitTarihh);
        if(sure<1){
                JOptionPane.showMessageDialog(null, " bu tarihte müsait değil \n Araba başka bi müşteri tarafından kiralandığı için", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
        sure = getDifferenceDays(currentDate,alisDate);

         if(sure<0){
                JOptionPane.showMessageDialog(null, "Tarihler bugünden önceki gün olamaz", "", JOptionPane.INFORMATION_MESSAGE);
         
         }else{
        sure = getDifferenceDays(alisDate,donusDate);
        if(sure<1){
                JOptionPane.showMessageDialog(null, "Alış tarihini dönüş tarihinden sonra giremezsiniz", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            int ucret = (int) (sure * aracKiralama.arabaninUcret);
        ucretLabel.setText(ucret +"");
        }
        
        } 
        } }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void alButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_alButtonMouseClicked

    private void alButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alButtonActionPerformed
     
              long sure;
         java.sql.Date musaitTarihh = Date.valueOf("4020-05-11");
         java.sql.Date currentDate = new java.sql.Date(Calendar.getInstance().getTime().getTime());
         java.sql.Date alisDate = new java.sql.Date(alisTarihi.getDate().getTime());
         java.sql.Date donusDate = new java.sql.Date(donusTarihi.getDate().getTime());
         try {
          musaitTarihh = Date.valueOf(aracKiralama.musaitTarih);

         }catch(Exception e) {
             
         
         }        sure = getDifferenceDays(donusDate,musaitTarihh);
        if(sure<1){
                JOptionPane.showMessageDialog(null, " bu tarihte müsait değil \n Araba başka bi müşteri tarafından kiralandığı için", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
        sure = getDifferenceDays(currentDate,alisDate);

         if(sure<0){
                JOptionPane.showMessageDialog(null, "Tarihler bugünden önceki gün olamaz", "", JOptionPane.INFORMATION_MESSAGE);
         
         }else{
        sure = getDifferenceDays(alisDate,donusDate);
        if(sure<1){
                JOptionPane.showMessageDialog(null, "Alış tarihini dönüş tarihinden sonra giremezsiniz", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
      db.arabaAl(aracKiralama.alMarka,aracKiralama.alModel,aracKiralama.musteriId, aracKiralama.arabaninId, alisDate, donusDate);
     JOptionPane.showMessageDialog(null, "Arabayı kiraladınız", "", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);  
        }       
         }}
        
        
    }//GEN-LAST:event_alButtonActionPerformed
public static long getDifferenceDays(Date d1, Date d2) {
    long diff = d2.getTime() - d1.getTime();
    return TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alButton;
    private org.jdesktop.swingx.JXDatePicker alisTarihi;
    private org.jdesktop.swingx.JXDatePicker donusTarihi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ucretLabel;
    // End of variables declaration//GEN-END:variables
}
